export const GET_BRANCHES = "GET_BRANCHES";
export const GET_BRANCH = "GET_BRANCH";
export const CREATE_BRANCH = "CREATE_BRANCH";
export const UPDATE_BRANCH = "UPDATE_BRANCH";
export const DELETE_BRANCH = "DELETE_BRANCH";
export const ENABLE_BRANCH = "ENABLE_BRANCH";
export const ERROR_BRANCH = "ERROR_BRANCH";
